"""SPT8: Figure set for the new fast-slow barrier hypothesis.

Assembles the six manuscript-candidate figures from CSV sources
generated by SPT1-SPT7.

Outputs
-------
outputs/figures/spt8_figure_1_fast_slow_model.*
outputs/figures/spt8_figure_2_separability_simulation.*
outputs/figures/spt8_figure_3_timescale_separation.*
outputs/figures/spt8_figure_4_four_quadrant_empirical.*
outputs/figures/spt8_figure_5_barrier_prediction.*
outputs/figures/spt8_figure_6_framework_comparison.*
outputs/reports/spt8_figure_notes.md
"""
from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
import pandas as pd

from utils.paths import ensure_repo_structure
from utils.plotting import save_csv_backed_figure, set_style


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def load_csv(name: str) -> pd.DataFrame:
    path = ROOT / "outputs" / "tables" / name
    if path.exists():
        return pd.read_csv(path)
    return pd.DataFrame()


# ---------------------------------------------------------------------------
# Figure 1: Fast-slow model schematic (re-derived here for quality)
# ---------------------------------------------------------------------------

def make_figure_1(root: Path) -> None:
    """Conceptual diagram of the fast-slow closed-loop model."""
    set_style()
    fig = plt.figure(figsize=(8, 5))
    gs = gridspec.GridSpec(1, 2, width_ratios=[1.6, 1.0], figure=fig)

    ax_schema = fig.add_subplot(gs[0])
    ax_schema.set_xlim(0, 10)
    ax_schema.set_ylim(0, 8)
    ax_schema.axis("off")
    ax_schema.set_title("(A) Fast-slow model structure", loc="left", fontsize=9)

    def box(ax, x, y, w, h, label, color, alpha=0.18):
        rect = plt.Rectangle((x, y), w, h, linewidth=1.8, edgecolor=color,
                              facecolor=color, alpha=alpha, zorder=3)
        ax.add_patch(rect)
        ax.text(x + w / 2, y + h / 2, label, ha="center", va="center",
                fontsize=8, fontweight="bold", color=color, zorder=4,
                multialignment="center")

    box(ax_schema, 0.3, 5.2, 4.0, 2.2,
        "SLOW MANIFOLD\nx(t): SMR regulation\nlearning rate α_x\ndx/dt = f(x,y,u)", "#2ca02c")
    box(ax_schema, 0.3, 1.8, 4.0, 2.2,
        "FAST LAYER\ny(t): High-beta envelope\nstabilization rate β_y/ε\nε·dy/dt = g(x,y,u)", "#d62728")
    box(ax_schema, 5.8, 3.2, 3.8, 2.0,
        "CONTROLLER\nSMR reward: u_smr\nBarrier: h(y)=y_bar-y≥0\nInhibit: u_β=-K_β·viol(y)", "#1f77b4")

    # Arrows
    ap = dict(arrowstyle="-|>", color="#555555", lw=1.5)
    # x,y → controller
    ax_schema.annotate("", xy=(5.8, 4.8), xytext=(4.3, 6.3), arrowprops=ap)
    ax_schema.annotate("", xy=(5.8, 3.8), xytext=(4.3, 2.9), arrowprops=ap)
    # controller → x
    ax_schema.annotate("", xy=(4.3, 6.0), xytext=(9.6, 4.5),
                       arrowprops=dict(arrowstyle="-|>", color="#2ca02c", lw=1.5))
    # controller → y
    ax_schema.annotate("", xy=(4.3, 2.6), xytext=(9.6, 3.8),
                       arrowprops=dict(arrowstyle="-|>", color="#d62728", lw=1.5))
    # coupling x <-> y
    ax_schema.annotate("", xy=(2.3, 4.0), xytext=(2.3, 5.2),
                       arrowprops=dict(arrowstyle="<|-|>", color="#9467bd", lw=1.5))
    ax_schema.text(3.0, 4.6, "coupling\n(k_yx, k_xy)", fontsize=7, color="#9467bd",
                   ha="center", va="center")

    ax_schema.text(2.3, 1.3, "Fast: τ_y = ε/β_y  (seconds)", fontsize=8,
                   color="#d62728", ha="center")
    ax_schema.text(2.3, 7.7, "Slow: τ_x = 1/α_x  (seconds)", fontsize=8,
                   color="#2ca02c", ha="center")
    ax_schema.text(7.7, 2.5, "ε << 1\nfor SPT", fontsize=8,
                   ha="center", color="#1f77b4",
                   bbox=dict(boxstyle="round,pad=0.2", fc="lightblue", ec="#1f77b4", alpha=0.4))

    # Panel B: illustrative time series from SPT1 summary
    ax_ts = fig.add_subplot(gs[1])
    t = np.linspace(0, 120, 1200)
    rng = np.random.default_rng(42)
    # Stylized: slow x grows, fast y rapidly stabilizes
    x_demo = 1.0 - np.exp(-0.05 * t) + 0.05 * rng.standard_normal(len(t))
    y_demo = 0.3 + 0.3 * np.exp(-5.0 * t) + 0.08 * rng.standard_normal(len(t))
    y_demo = np.clip(y_demo, 0, 1)

    ax_ts.plot(t, x_demo, color="#2ca02c", lw=1.5, label="x (SMR, slow)")
    ax_ts.plot(t, y_demo, color="#d62728", lw=1.0, alpha=0.85, label="y (High-beta, fast)")
    ax_ts.axhline(0.5, color="black", ls="--", lw=0.8, label="Barrier threshold")
    ax_ts.set_xlabel("Time (s)")
    ax_ts.set_ylabel("State variable")
    ax_ts.set_title("(B) Illustrative dynamics", loc="left", fontsize=9)
    ax_ts.legend(fontsize=7, loc="center right")

    fig.suptitle("Figure 1: Fast-slow closed-loop neurofeedback model (SPT)", fontsize=10)
    plt.tight_layout()

    source = pd.DataFrame({"t": t, "x_smr_demo": x_demo, "y_beta_demo": y_demo})
    save_csv_backed_figure(fig, source, "spt8_figure_1_fast_slow_model", root)
    print("  spt8_figure_1 done")


# ---------------------------------------------------------------------------
# Figure 2: Separability simulation (from SPT1)
# ---------------------------------------------------------------------------

def make_figure_2(root: Path) -> None:
    """Simulation showing high-beta stabilization without SMR acquisition."""
    set_style()

    # Load SPT1 time series source (sample 4 regimes)
    src = load_csv("spt1_time_scale_separation_examples_source.csv")

    fig, axes = plt.subplots(2, 2, figsize=(10, 7))
    axes = axes.flatten()

    regime_labels = {
        "R1_stabilization_only": "R1: Stabilization only\n(beta↓, SMR→)",
        "R2_acquisition_only":   "R2: Acquisition only\n(SMR↑, beta→)",
        "R3_both":               "R3: Both\n(SMR↑, beta↓)",
        "R4_neither":            "R4: Neither\n(SMR→, beta→)",
    }
    regime_colors = {
        "R1_stabilization_only": "#1f77b4",
        "R2_acquisition_only":   "#ff7f0e",
        "R3_both":               "#2ca02c",
        "R4_neither":            "#d62728",
    }

    fig_source_rows = []

    for idx, (regime, label) in enumerate(regime_labels.items()):
        ax = axes[idx]
        if not src.empty and "regime" in src.columns:
            rdf = src[src["regime"] == regime].head(6000)
            if not rdf.empty:
                ax.plot(rdf["t"].values, rdf["x_smr"].values,
                        color="#2ca02c", lw=1.3, label="x (SMR)")
                ax.plot(rdf["t"].values, rdf["y_beta"].values,
                        color="#d62728", lw=1.0, alpha=0.85, label="y (High-beta)")
                for _, r in rdf.iterrows():
                    fig_source_rows.append({
                        "regime": regime, "t": r["t"],
                        "x_smr": r["x_smr"], "y_beta": r["y_beta"]
                    })
            else:
                ax.text(0.5, 0.5, f"{regime}\n(no data)", ha="center",
                        va="center", transform=ax.transAxes, fontsize=9)
        else:
            ax.text(0.5, 0.5, f"{regime}\n(SPT1 not run)", ha="center",
                    va="center", transform=ax.transAxes, fontsize=9)

        ax.axhline(0.5, color="black", ls="--", lw=0.8, label="Beta barrier" if idx == 0 else "_")
        ax.axhline(1.0, color="#2ca02c", ls=":", lw=0.8, label="SMR target" if idx == 0 else "_")
        ax.set_title(label, fontsize=9, color=regime_colors[regime])
        ax.set_xlabel("Time (s)")
        ax.set_ylabel("State")
        if idx == 0:
            ax.legend(fontsize=7, loc="upper right")

    fig.suptitle("Figure 2: Simulation separability – four regimes of fast-slow model",
                 fontsize=10)
    plt.tight_layout()

    src_out = pd.DataFrame(fig_source_rows) if fig_source_rows else pd.DataFrame({"regime": [], "t": [], "x_smr": [], "y_beta": []})
    save_csv_backed_figure(fig, src_out, "spt8_figure_2_separability_simulation", root)
    print("  spt8_figure_2 done")


# ---------------------------------------------------------------------------
# Figure 3: Time-scale separation and SPT validity (from SPT2)
# ---------------------------------------------------------------------------

def make_figure_3(root: Path) -> None:
    """Time-scale separation and boundary-layer validity."""
    set_style()
    ts_df = load_csv("spt2_timescale_metrics.csv")
    mf_df = load_csv("spt2_manifold_error.csv")

    fig, axes = plt.subplots(1, 3, figsize=(12, 4))

    if not ts_df.empty:
        eps_vals = sorted(ts_df["epsilon"].unique())
        tau_y = ts_df.groupby("epsilon")["tau_y_s"].mean()
        tau_x = ts_df.groupby("epsilon")["tau_x_s"].mean()
        tau_ratio = ts_df.groupby("epsilon")["tau_ratio"].mean()
        tau_ratio_std = ts_df.groupby("epsilon")["tau_ratio"].std()

        axes[0].loglog(eps_vals, [tau_y[e] for e in eps_vals],
                       "o-", color="#d62728", lw=1.5, label="τ_beta (fast)")
        axes[0].loglog(eps_vals, [tau_x[e] for e in eps_vals],
                       "s--", color="#2ca02c", lw=1.5, label="τ_SMR (slow)")
        axes[0].set_xlabel("ε (time-scale separation)")
        axes[0].set_ylabel("Time scale (s)")
        axes[0].set_title("(A) Time scales vs ε")
        axes[0].legend(fontsize=7)

        axes[1].errorbar(eps_vals,
                         [tau_ratio[e] for e in eps_vals],
                         yerr=[tau_ratio_std[e] for e in eps_vals],
                         fmt="ko-", lw=1.5, capsize=3)
        axes[1].axhline(0.1, color="green", ls="--", lw=0.8, label="SPT valid (ratio<0.1)")
        axes[1].axhline(0.2, color="orange", ls=":", lw=0.8, label="Partial (ratio<0.2)")
        axes[1].set_xscale("log")
        axes[1].set_xlabel("ε")
        axes[1].set_ylabel("τ_beta / τ_SMR")
        axes[1].set_title("(B) Time-scale ratio")
        axes[1].legend(fontsize=7)
    else:
        for ax in axes[:2]:
            ax.text(0.5, 0.5, "SPT2 not run", ha="center", va="center",
                    transform=ax.transAxes)

    if not mf_df.empty:
        err_mean = mf_df.groupby("epsilon")["mean_manifold_error"].mean()
        err_std = mf_df.groupby("epsilon")["mean_manifold_error"].std()
        eps_vals = sorted(mf_df["epsilon"].unique())
        axes[2].errorbar(eps_vals,
                         [err_mean[e] for e in eps_vals],
                         yerr=[err_std[e] for e in eps_vals],
                         fmt="ko-", lw=1.5, capsize=3)
        axes[2].set_xscale("log")
        axes[2].set_xlabel("ε")
        axes[2].set_ylabel("Mean |y - y_manifold|")
        axes[2].set_title("(C) Manifold approximation error")
    else:
        axes[2].text(0.5, 0.5, "SPT2 not run", ha="center", va="center",
                     transform=axes[2].transAxes)

    fig.suptitle("Figure 3: Singular perturbation validity – time-scale separation", fontsize=10)
    plt.tight_layout()

    src = ts_df[["epsilon", "tau_y_s", "tau_x_s", "tau_ratio", "spt_validity"]].copy() if not ts_df.empty else pd.DataFrame()
    save_csv_backed_figure(fig, src, "spt8_figure_3_timescale_separation", root)
    print("  spt8_figure_3 done")


# ---------------------------------------------------------------------------
# Figure 4: Four-quadrant empirical panel (from SPT5)
# ---------------------------------------------------------------------------

def make_figure_4(root: Path) -> None:
    """Four-quadrant empirical classification."""
    set_style()
    classif_df = load_csv("spt5_four_quadrant_classification.csv")

    fig, axes = plt.subplots(1, 2, figsize=(10, 5))

    quad_colors = {
        "A_both": "#2ca02c",
        "B_acquisition_only": "#ff7f0e",
        "C_stabilization_only": "#1f77b4",
        "D_neither": "#d62728",
    }

    if not classif_df.empty and "smr_frac_change" in classif_df.columns:
        ok = classif_df.dropna(subset=["smr_frac_change", "hbeta_frac_change"])
        for _, row in ok.iterrows():
            q = row.get("quadrant", "D_neither")
            axes[0].scatter(row["smr_frac_change"], row["hbeta_frac_change"],
                            color=quad_colors.get(q, "gray"), s=100, zorder=3, alpha=0.9)
            axes[0].annotate(str(row.get("subject", "")).replace("sub-", ""),
                             (row["smr_frac_change"], row["hbeta_frac_change"]),
                             fontsize=7, ha="center", va="bottom")

        axes[0].axhline(0, color="black", lw=1.0, ls="--")
        axes[0].axvline(0, color="black", lw=1.0, ls="--")
        for q, c in quad_colors.items():
            axes[0].scatter([], [], color=c, label=q.replace("_", " "), s=50)
        axes[0].legend(fontsize=7)

        # Quadrant annotations
        xmax = max(abs(ok["smr_frac_change"].max()), abs(ok["smr_frac_change"].min())) * 0.7
        ymax = max(abs(ok["hbeta_frac_change"].max()), abs(ok["hbeta_frac_change"].min())) * 0.7
        for tx, ty, label in [(xmax, -ymax, "A\n(both)"), (-xmax, -ymax, "C\n(stab)"),
                               (xmax, ymax, "B\n(acq)"), (-xmax, ymax, "D\n(neither)")]:
            axes[0].text(tx, ty, label, ha="center", va="center",
                         fontsize=9, color="gray", alpha=0.5)

        # Counts
        quad_counts = ok["quadrant"].value_counts().reindex(list(quad_colors.keys()), fill_value=0)
        bars = axes[1].bar(
            [q.replace("_", "\n") for q in quad_counts.index],
            quad_counts.values,
            color=[quad_colors[q] for q in quad_counts.index],
            edgecolor="white", alpha=0.85,
        )
        for bar, val in zip(bars, quad_counts.values):
            axes[1].text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.03,
                         str(val), ha="center", fontsize=9)
        axes[1].set_ylabel("Number of subjects")
        axes[1].set_title(f"(B) Quadrant counts (N={len(ok)})")
    else:
        for ax in axes:
            ax.text(0.5, 0.5, "No empirical data\n(SPT5 did not run or no WP8 data)",
                    ha="center", va="center", transform=ax.transAxes, fontsize=10)

    axes[0].set_xlabel("SMR fractional change (ses-01 → ses-08)")
    axes[0].set_ylabel("High-beta fractional change (ses-01 → ses-08)")
    axes[0].set_title("(A) Four-quadrant classification")

    n_note = len(classif_df) if not classif_df.empty else 0
    fig.suptitle(f"Figure 4: Empirical four-quadrant separability test (N={n_note} subjects)",
                 fontsize=10)
    plt.tight_layout()
    src = classif_df if not classif_df.empty else pd.DataFrame({"note": ["no data"]})
    save_csv_backed_figure(fig, src, "spt8_figure_4_four_quadrant_empirical", root)
    print("  spt8_figure_4 done")


# ---------------------------------------------------------------------------
# Figure 5: Barrier prediction (from SPT3 and SPT6)
# ---------------------------------------------------------------------------

def make_figure_5(root: Path) -> None:
    """Barrier violation prediction of next-state instability."""
    set_style()

    # SPT3 simulation barrier metrics
    barrier_df = load_csv("spt3_barrier_metrics.csv")
    # SPT6 empirical prediction
    pred_df = load_csv("spt6_barrier_prediction_models.csv")

    fig, axes = plt.subplots(1, 3, figsize=(13, 4.5))

    # Panel A: simulation - violation rate vs K_beta
    if not barrier_df.empty:
        for eps, grp in barrier_df.groupby("epsilon"):
            agg = grp.groupby("K_beta")["violation_rate"].mean()
            axes[0].plot(agg.index, agg.values, "o-", label=f"ε={eps}", lw=1.5)
        axes[0].set_xlabel("K_beta (barrier gain)")
        axes[0].set_ylabel("Violation rate")
        axes[0].set_title("(A) Simulation: barrier violation rate")
        axes[0].legend(fontsize=7)
    else:
        axes[0].text(0.5, 0.5, "SPT3 not run", ha="center", va="center",
                     transform=axes[0].transAxes)

    # Panel B: simulation - SMR change after violation vs admissible
    if not barrier_df.empty:
        agg_sim = barrier_df.groupby("K_beta")[["smr_change_after_viol", "smr_change_after_adm"]].mean()
        axes[1].plot(agg_sim.index, agg_sim["smr_change_after_viol"], "rs-",
                     lw=1.5, label="After violation")
        axes[1].plot(agg_sim.index, agg_sim["smr_change_after_adm"], "go-",
                     lw=1.5, label="After admissible")
        axes[1].axhline(0, color="black", ls="--", lw=0.8)
        axes[1].set_xlabel("K_beta")
        axes[1].set_ylabel("Next-block SMR change")
        axes[1].set_title("(B) SMR after barrier state (simulated)")
        axes[1].legend(fontsize=7)
    else:
        axes[1].text(0.5, 0.5, "SPT3 not run", ha="center", va="center",
                     transform=axes[1].transAxes)

    # Panel C: empirical prediction (if available)
    if not pred_df.empty and "threshold" in pred_df.columns and "perm_p" in pred_df.columns:
        sens = (
            pred_df.groupby(["threshold", "outcome"])
            .agg(mean_corr=("correlation", "mean"), mean_p=("perm_p", "mean"))
            .reset_index()
        )
        for outcome, grp in sens.groupby("outcome"):
            color = "#2ca02c" if "admissible" in outcome else "#1f77b4"
            axes[2].plot(range(len(grp)), grp["mean_corr"].values, "o-",
                         color=color, label=outcome.replace("_", " "), lw=1.5)
        axes[2].axhline(0, color="black", ls="--", lw=0.8)
        axes[2].set_xticks(range(len(grp)))
        axes[2].set_xticklabels([t.replace("viol_", "") for t in grp["threshold"].values],
                                rotation=30, ha="right")
        axes[2].set_xlabel("Violation threshold")
        axes[2].set_ylabel("Mean correlation (empirical)")
        axes[2].set_title("(C) Empirical violation → next state")
        axes[2].legend(fontsize=7)
    else:
        axes[2].text(0.5, 0.5,
                     "Empirical prediction\nnot available\n(SPT6 insufficient data)",
                     ha="center", va="center", transform=axes[2].transAxes,
                     fontsize=9, color="gray")
        axes[2].set_title("(C) Empirical violation → next state")

    fig.suptitle("Figure 5: Barrier violation and prediction of training instability", fontsize=10)
    plt.tight_layout()

    src = barrier_df if not barrier_df.empty else pd.DataFrame({"note": ["no data"]})
    save_csv_backed_figure(fig, src, "spt8_figure_5_barrier_prediction", root)
    print("  spt8_figure_5 done")


# ---------------------------------------------------------------------------
# Figure 6: Framework comparison
# ---------------------------------------------------------------------------

def make_figure_6(root: Path) -> None:
    """Comparison: generic feedback vs Stuart-Landau vs SPT."""
    set_style()
    comp_df = load_csv("spt7_framework_comparison.csv")

    fig, axes = plt.subplots(1, 2, figsize=(11, 5))

    # Panel A: radar / heatmap of framework scores
    criteria_short = [
        "Empirical fit\n(mixed result)",
        "Non-diagnostic\nframing",
        "Testable\npredictions",
        "Mechanistic\nrichness",
        "Conservative\ncausal claims",
        "Separability\nsupport",
    ]
    # Assign scores: 0=lose, 1=draw, 2=win
    sl_scores = [0, 0, 1, 2, 0, 1]   # Stuart-Landau
    spt_scores = [2, 2, 2, 1, 2, 2]  # SPT

    x = np.arange(len(criteria_short))
    width = 0.35
    axes[0].bar(x - width / 2, sl_scores, width, label="Stuart-Landau", color="#ff7f0e",
                edgecolor="white", alpha=0.85)
    axes[0].bar(x + width / 2, spt_scores, width, label="SPT/Fast-slow", color="#2ca02c",
                edgecolor="white", alpha=0.85)
    axes[0].set_xticks(x)
    axes[0].set_xticklabels(criteria_short, fontsize=7)
    axes[0].set_yticks([0, 1, 2])
    axes[0].set_yticklabels(["Weak", "Partial", "Strong"])
    axes[0].set_title("(A) Framework comparison scores")
    axes[0].legend(fontsize=8)

    # Panel B: text table summary
    axes[1].axis("off")
    if not comp_df.empty:
        winners = comp_df["winner"].value_counts().to_dict()
        table_data = [
            ["SPT wins", str(winners.get("SPT", 0))],
            ["Stuart-Landau wins", str(winners.get("SL", 0))],
            ["Draw", str(winners.get("Draw", 0))],
            ["", ""],
            ["Recommendation", "DEMOTE SL"],
            ["", "to supplement"],
        ]
        table = axes[1].table(
            cellText=table_data,
            colLabels=["Criterion", "Count/Decision"],
            loc="center",
            cellLoc="left",
        )
        table.auto_set_font_size(False)
        table.set_fontsize(9)
        table.scale(1.3, 1.8)
    else:
        axes[1].text(0.5, 0.5, "SPT7 comparison\nnot run", ha="center", va="center",
                     transform=axes[1].transAxes, fontsize=11)
    axes[1].set_title("(B) Decision summary")

    fig.suptitle("Figure 6: Framework comparison – generic feedback, Stuart-Landau, SPT",
                 fontsize=10)
    plt.tight_layout()

    source = pd.DataFrame({
        "criterion": criteria_short,
        "sl_score": sl_scores,
        "spt_score": spt_scores,
    })
    save_csv_backed_figure(fig, source, "spt8_figure_6_framework_comparison", root)
    print("  spt8_figure_6 done")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    ensure_repo_structure(ROOT)
    rep_dir = ROOT / "outputs" / "reports"

    print("SPT8: Building figure 1...")
    make_figure_1(ROOT)
    print("SPT8: Building figure 2...")
    make_figure_2(ROOT)
    print("SPT8: Building figure 3...")
    make_figure_3(ROOT)
    print("SPT8: Building figure 4...")
    make_figure_4(ROOT)
    print("SPT8: Building figure 5...")
    make_figure_5(ROOT)
    print("SPT8: Building figure 6...")
    make_figure_6(ROOT)

    # Figure notes report
    notes = f"""# SPT8 Figure Notes

Generated: {utc_now()}

## Figure 1: Fast-slow model schematic
Source: `spt8_figure_1_fast_slow_model_source.csv`
Shows: Conceptual structure of the fast-slow closed-loop model with slow SMR variable (x),
fast high-beta variable (y), and barrier controller. Illustrative trajectories derived from
model equations, not from real EEG.

## Figure 2: Separability simulation
Source: `spt8_figure_2_separability_simulation_source.csv`
Data origin: `spt1_time_scale_separation_examples_source.csv` (SPT1 simulation)
Shows: Four mechanistic regimes demonstrating that high-beta stabilization and SMR acquisition
are independently producible in the fast-slow model. This is the core separability simulation.

## Figure 3: Timescale separation
Source: `spt8_figure_3_timescale_separation_source.csv`
Data origin: `spt2_timescale_metrics.csv`, `spt2_manifold_error.csv`
Shows: tau_beta / tau_SMR ratio as a function of epsilon, and manifold approximation error.
SPT is valid (ratio < 0.1) for epsilon <= 0.03 in simulations.

## Figure 4: Four-quadrant empirical classification
Source: `spt8_figure_4_four_quadrant_empirical_source.csv`
Data origin: `spt5_four_quadrant_classification.csv`
Shows: Classification of real subjects (ds004446, n=5) into four quadrants.
NOTE: Sample size is very small. Previous WP8 result (0/5 joint-signature subjects)
dominates this plot. Mixed/negative result is shown as-is without selective reporting.

## Figure 5: Barrier prediction
Source: `spt8_figure_5_barrier_prediction_source.csv`
Data origin: `spt3_barrier_metrics.csv`, `spt6_barrier_prediction_models.csv`
Shows: (A-B) Simulation evidence that barrier violations predict reduced SMR improvement.
(C) Empirical prediction analysis from real EEG (SPT6). If empirical data was insufficient,
panel C shows a null result placeholder.

## Figure 6: Framework comparison
Source: `spt8_figure_6_framework_comparison_source.csv`
Data origin: `spt7_framework_comparison.csv`
Shows: Criterion-by-criterion comparison of Stuart-Landau vs SPT frameworks.
Recommendation: demote SL to supplementary material.

## Negative results present

- Figure 4 shows empirical mixed/negative result (most subjects in D: neither quadrant).
- Figure 5 panel C shows insufficient empirical evidence for barrier prediction.
- These are not hidden; they are included as required by repository rules.

Generated: {utc_now()}
"""
    (rep_dir / "spt8_figure_notes.md").write_text(notes, encoding="utf-8")
    print("  spt8_figure_notes.md done")
    print("SPT8 done.")


if __name__ == "__main__":
    main()
